const MAX_FILE_BYTES = 1024 * 1024;

const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function shell(title, body, script = '') {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="把一个文件变成可直接打开的临时网页"><title>${esc(title)} · SoloDrop</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#181824;background:#f5f5fa;--brand:#5b5ce2;--muted:#676978;--line:#dedfe9}*{box-sizing:border-box}body{margin:0}a{color:#4d4ec8}.nav{height:64px;display:flex;align-items:center;justify-content:space-between;width:min(100% - 32px,1080px);margin:auto}.logo{font-weight:850;font-size:20px}.navlinks{display:flex;gap:18px;align-items:center}.navlinks a{text-decoration:none;font-weight:650}.page{width:min(100% - 32px,1080px);margin:56px auto 90px}.hero{display:grid;grid-template-columns:1fr 460px;gap:64px;align-items:center}.hero h1{font-size:clamp(42px,7vw,72px);line-height:1.02;letter-spacing:-.055em;margin:0}.hero p{font-size:19px;line-height:1.65;color:var(--muted)}.card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:22px;box-shadow:0 24px 70px #27285018}.drop{min-height:250px;border:2px dashed #c6c7d5;border-radius:16px;display:grid;place-items:center;text-align:center;padding:24px;cursor:pointer}.drop.drag{border-color:var(--brand);background:#f1f1ff}.drop strong{font-size:21px}.drop span{display:block;margin-top:8px;color:var(--muted)}button,.button{min-height:46px;border:0;border-radius:11px;padding:0 18px;background:var(--brand);color:#fff;font:inherit;font-weight:750;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}button:disabled{opacity:.48}.field{display:grid;gap:7px;margin:15px 0}.field input{height:48px;border:1px solid var(--line);border-radius:11px;padding:0 13px;font:inherit}.muted,.status{color:var(--muted);line-height:1.55}.status{min-height:24px}.check{display:flex;align-items:flex-start;gap:9px;margin:14px 0;font-size:14px;line-height:1.45}.check input{margin-top:3px}.full{width:100%}.auth{width:min(100% - 32px,430px);margin:52px auto}.auth h1{margin-bottom:8px}.tabs{display:flex;gap:12px;margin-top:18px}.result{padding:16px;background:#f3f3ff;border-radius:12px}.history{margin-top:42px}.item{display:grid;grid-template-columns:1fr auto;gap:8px;padding:16px 0;border-bottom:1px solid var(--line)}@media(max-width:800px){.hero{grid-template-columns:1fr}.page{margin-top:30px}.navlinks .optional{display:none}}@media(max-width:520px){.hero h1{font-size:43px}.card{padding:14px}.drop{min-height:210px}}
</style></head><body><nav class="nav"><a class="logo" href="/">SoloDrop</a><div class="navlinks"><a class="optional" href="https://marketplace.visualstudio.com/items?itemName=SZLK.solodrop">安装 VS Code 插件</a><a href="/account">我的记录</a></div></nav>${body}<footer class="page muted"><a href="/terms">服务条款</a> · <a href="/privacy">隐私政策</a> · <a href="/legal-supplement">产品补充说明</a></footer>${script}</body></html>`;
}

function homePage(user) {
  const gate = user ? `<input id="file" type="file" hidden><label id="drop" class="drop" for="file"><div><strong>拖入一个文件</strong><span>或点击从电脑选择，最大 1 MB</span></div></label><p id="picked" class="muted">支持 Markdown、代码、文本、图片、CSV、HTML 和小型 PDF</p><label class="check"><input id="terms" type="checkbox"> <span>我同意 <a href="https://www.cloudflare.com/terms/" target="_blank">Cloudflare 服务条款</a>和<a href="https://www.cloudflare.com/privacypolicy/" target="_blank">隐私政策</a>，并理解分享页是公开链接，未认领的临时 Worker 约 60 分钟后由 Cloudflare 删除。</span></label><button id="share" class="full" disabled>生成临时分享页</button><p id="status" class="status" aria-live="polite"></p><div id="result" class="result" hidden><strong>分享页已生成</strong><p><a id="short" target="_blank"></a></p><p><a id="claim" target="_blank" rel="noreferrer">认领到我的 Cloudflare 账号</a></p></div>` : `<div class="drop"><div><strong>先登录后开始分享</strong><span>文件不会保存在 SoloDrop；登录用于保护认领链接和保留活动记录。</span></div></div><div class="tabs"><a class="button" href="/login">登录</a><a class="button" href="/register">注册</a></div>`;
  const script = user ? `<script src="/pow.js"></script><script>window.SoloDrop.initShare(${MAX_FILE_BYTES})</script>` : '';
  return shell('临时分享文件', `<main class="page"><section class="hero"><div><h1>一个文件，<br>一个临时网页。</h1><p>无需安装。SoloDrop 把文件直接交给 Cloudflare 创建临时 Worker，并返回可分享的短链接。我们只保留活动记录，不保存文件内容。</p><p class="muted">需要在 VS Code 里反复分享？安装插件会更顺手。</p></div><div class="card">${gate}</div></section></main>`, script);
}

function authPage(mode, message = '') {
  const register = mode === 'register';
  return shell(register ? '注册' : '登录', `<main class="auth card"><h1>${register ? '创建 SoloDrop 账号' : '欢迎回来'}</h1><p class="muted">账号由 SZLKPassport 安全管理。</p>${message ? `<p class="result">${esc(message)}</p>` : ''}<form method="post" action="/api/auth/${mode}">${register ? '<label class="field">昵称<input name="name" autocomplete="name" maxlength="80"></label>' : ''}<label class="field">邮箱<input type="email" name="email" autocomplete="email" required></label><label class="field">密码<input type="password" name="password" autocomplete="${register ? 'new-password' : 'current-password'}" minlength="8" required></label><button class="full">${register ? '注册' : '登录'}</button></form><p class="muted">${register ? '已有账号？<a href="/login">直接登录</a>' : '还没有账号？<a href="/register">立即注册</a> · <a href="/forgot">忘记密码</a>'}</p></main>`);
}

function accountPage(user, activities) {
  const rows = activities.length ? activities.map((x) => `<div class="item"><div><strong>${esc(x.file_name)}</strong><div class="muted">${Math.ceil(x.size_bytes / 1024)} KB · ${new Date(x.created_at).toLocaleString('zh-CN')} · ${esc(x.status)}</div></div>${x.short_slug ? `<a href="/${esc(x.short_slug)}" target="_blank">打开</a>` : ''}</div>`).join('') : '<p class="muted">还没有分享记录。</p>';
  return shell('我的记录', `<main class="page"><h1>${esc(user.name || user.email)}</h1><p class="muted">这里只保留分享时间、文件名、大小和结果状态，不保存文件内容。</p><p><a href="/api/auth/logout">退出登录</a></p><section class="history"><h2>最近活动</h2>${rows}</section></main>`);
}

function legalPage(title, document) {
  const groups = document?.composition || document?.supplement?.composition || [];
  const sections = groups.flatMap((group) => group.sections || []).map((section) => `<section><h2>${esc(section.title)}</h2><p>${esc(section.body_markdown || section.body || '').replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>')}</p></section>`).join('');
  return shell(title, `<main class="page card"><h1>${esc(document?.title || title)}</h1>${sections || '<p class="muted">法律文件暂时无法加载，请稍后重试。</p>'}</main>`);
}

export { MAX_FILE_BYTES, accountPage, authPage, homePage, legalPage, shell };
